version: '2'
services:
  cassandra:
    build: ./cassandra
    image: cassandra
    ports:
      - "9160:9160"
      - "9042:9042"

  elasticsearch:
    build: ./elasticsearch
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

  janusgraph:
    build: ./janusgraph
    image: janusgraph
    ports:
      - "8182:8182"
    depends_on:
      - cassandra
      - elasticsearch
