version: '2'
services:
  zookeeper:
    image: zookeeper
    restart: always
    ports:
      - "2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888

  nifi:
    build: ./nifi
    image: nifi
    environment:
      - EXCLUDE_PORTS=8081,8082
        #Used by ListenTCP or other processors. Depends on the data flow.
      - TCP_PORTS=9001
      - NIFI_HOME=/opt/nifi
    depends_on:
      - zookeeper
  
  lb-nifi:
    image: dockercloud/haproxy
    links:
      - nifi
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "9001:9001"
  
  kafka:
    build: ./kafka
    image: kafka
    ports:
      - "9092"
    environment:
      - KAFKA_PORT=9092
    depends_on:
      - zookeeper

  storm-nimbus:
    build: ./storm/nimbus
    image: storm-nimbus
    ports:
      - "13772:3772"
      - "13773:3773"
      - "16627:6627"
    depends_on:
      - zookeeper
 
  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "10000:9000"
  
  zk-web:
    image: tobilg/zookeeper-webui
    ports:
      - "10001:8080"
    environment:
      - USER=admin
      - PASSWORD=passwr0rd
      - ZK_DEFAULT_NODE=zookeeper:2181
    depends_on:
      - zookeeper
  
  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - "10002:9000"
    environment:
      - ZK_HOSTS=zookeeper:2181
      - APPLICATION_SECRET=kafka-manager
    depends_on:
      - zookeeper
      - kafka
